=== NicolasBi/RushDroid/app/src/main/assets/rushpuzzles.dtd
<!DOCTYPE rushpuzzles [

<!ELEMENT rushpuzzles (puzzle)>
<!ELEMENT puzzle (piece)>
    <!ATTLIST puzzle name CDATA #REQUIRED>
    <!ATTLIST puzzle monde CDATA #REQUIRED>
<!ELEMENT piece EMPTY>
    <!ATTLIST piece id ID #REQUIRED>
    <!ATTLIST piece len (2|3) #REQUIRED>
    <!ATTLIST piece dir (H|V) #REQUIRED>
    <!ATTLIST piece col CDATA #REQUIRED>
    <!ATTLIST piece lig CDATA #REQUIRED>
]>

=== NicolasBi/RushDroid/app/src/main/assets/rushpuzzles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rushpuzzles SYSTEM "rushpuzzles.dtd">
<rushpuzzles>
  <puzzle name="pb0" monde="0">
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
  </puzzle>
  <puzzle name="pb1" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="0"/>
    <piece id="2" len="3" dir="V" col="0" lig="1"/>
    <piece id="3" len="2" dir="V" col="0" lig="4"/>
    <piece id="4" len="3" dir="V" col="3" lig="1"/>
    <piece id="5" len="3" dir="H" col="2" lig="5"/>
    <piece id="6" len="2" dir="H" col="4" lig="4"/>
    <piece id="7" len="3" dir="V" col="5" lig="0"/>
  </puzzle>
  <puzzle name="pb2" monde="1">
    <!-- Fait par Amina Djelloul -->
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="3" dir="V" col="0" lig="1"/>
    <piece id="2" len="2" dir="V" col="0" lig="4"/>
    <piece id="3" len="3" dir="V" col="3" lig="0"/>
    <piece id="4" len="3" dir="H" col="3" lig="5"/>
    <piece id="5" len="2" dir="H" col="4" lig="0"/>
    <piece id="6" len="3" dir="V" col="5" lig="2"/>
  </puzzle>
  <puzzle name="pb3" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="H" col="1" lig="3"/>
    <piece id="2" len="2" dir="V" col="1" lig="4"/>
    <piece id="3" len="2" dir="H" col="2" lig="5"/>
    <piece id="4" len="3" dir="V" col="3" lig="2"/>
    <piece id="5" len="3" dir="V" col="5" lig="3"/>
  </puzzle>
  <puzzle name="pb4" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="3" dir="V" col="0" lig="0"/>
    <piece id="2" len="2" dir="V" col="2" lig="3"/>
    <piece id="3" len="3" dir="H" col="2" lig="5"/>
    <piece id="4" len="3" dir="V" col="3" lig="0"/>
    <piece id="5" len="3" dir="H" col="3" lig="3"/>
    <piece id="6" len="2" dir="V" col="5" lig="4"/>
  </puzzle>
  <puzzle name="pb5" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="0"/>
    <piece id="2" len="3" dir="V" col="0" lig="1"/>
    <piece id="3" len="2" dir="V" col="0" lig="4"/>
    <piece id="4" len="3" dir="H" col="1" lig="3"/>
    <piece id="5" len="3" dir="V" col="3" lig="0"/>
    <piece id="6" len="3" dir="V" col="4" lig="1"/>
    <piece id="7" len="2" dir="H" col="4" lig="4"/>
    <piece id="8" len="2" dir="H" col="4" lig="5"/>
    <piece id="9" len="2" dir="V" col="5" lig="0"/>
    <piece id="10" len="2" dir="V" col="5" lig="2"/>
  </puzzle>
  <puzzle name="pb6" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="0"/>
    <piece id="2" len="2" dir="H" col="0" lig="1"/>
    <piece id="3" len="2" dir="H" col="0" lig="3"/>
    <piece id="4" len="2" dir="V" col="0" lig="4"/>
    <piece id="5" len="2" dir="V" col="2" lig="3"/>
    <piece id="6" len="2" dir="V" col="3" lig="0"/>
    <piece id="7" len="3" dir="V" col="3" lig="2"/>
    <piece id="8" len="3" dir="H" col="3" lig="5"/>
    <piece id="9" len="3" dir="V" col="4" lig="1"/>
    <piece id="10" len="3" dir="V" col="5" lig="1"/>
  </puzzle>
  <puzzle name="pb7" monde="1">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="V" col="1" lig="0"/>
    <piece id="2" len="2" dir="H" col="2" lig="0"/>
    <piece id="3" len="2" dir="H" col="2" lig="3"/>
    <piece id="4" len="2" dir="V" col="3" lig="1"/>
    <piece id="5" len="2" dir="V" col="3" lig="4"/>
    <piece id="6" len="2" dir="V" col="4" lig="0"/>
    <piece id="7" len="2" dir="V" col="5" lig="0"/>
    <piece id="8" len="2" dir="V" col="5" lig="2"/>
  </puzzle>
  <puzzle name="pb8" monde="1">
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="3"/>
    <piece id="2" len="2" dir="H" col="0" lig="4"/>
    <piece id="3" len="2" dir="H" col="0" lig="5"/>
    <piece id="4" len="2" dir="H" col="2" lig="1"/>
    <piece id="5" len="2" dir="V" col="2" lig="2"/>
    <piece id="6" len="2" dir="V" col="2" lig="4"/>
    <piece id="7" len="2" dir="H" col="3" lig="0"/>
    <piece id="8" len="2" dir="V" col="3" lig="2"/>
    <piece id="9" len="3" dir="H" col="3" lig="4"/>
    <piece id="10" len="3" dir="H" col="3" lig="5"/>
    <piece id="11" len="2" dir="V" col="4" lig="1"/>
    <piece id="12" len="2" dir="H" col="4" lig="3"/>
    <piece id="13" len="3" dir="V" col="5" lig="0"/>
  </puzzle>
  <puzzle name="pb9" monde="2">
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
    <piece id="1" len="3" dir="V" col="0" lig="3"/>
    <piece id="2" len="2" dir="V" col="1" lig="0"/>
    <piece id="3" len="3" dir="H" col="1" lig="3"/>
    <piece id="4" len="2" dir="H" col="2" lig="0"/>
    <piece id="5" len="2" dir="V" col="2" lig="4"/>
    <piece id="6" len="2" dir="V" col="3" lig="1"/>
    <piece id="7" len="2" dir="H" col="4" lig="0"/>
    <piece id="8" len="2" dir="H" col="4" lig="1"/>
    <piece id="9" len="3" dir="V" col="4" lig="2"/>
    <piece id="10" len="2" dir="V" col="5" lig="2"/>
    <piece id="11" len="2" dir="V" col="5" lig="4"/>
  </puzzle>
  <puzzle name="pb10" monde="2">
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
    <piece id="1" len="2" dir="V" col="0" lig="0"/>
    <piece id="2" len="2" dir="H" col="1" lig="1"/>
    <piece id="3" len="2" dir="V" col="2" lig="2"/>
    <piece id="4" len="2" dir="V" col="2" lig="4"/>
    <piece id="5" len="3" dir="H" col="3" lig="0"/>
    <piece id="6" len="2" dir="V" col="3" lig="1"/>
    <piece id="7" len="2" dir="H" col="3" lig="4"/>
    <piece id="8" len="3" dir="H" col="3" lig="5"/>
    <piece id="9" len="3" dir="V" col="5" lig="2"/>
  </puzzle>
  <puzzle name="pb11" monde="2">
    <piece id="0" len="2" dir="H" col="2" lig="2"/>
    <piece id="1" len="3" dir="H" col="0" lig="0"/>
    <piece id="2" len="2" dir="V" col="0" lig="1"/>
    <piece id="3" len="2" dir="H" col="0" lig="3"/>
    <piece id="4" len="2" dir="H" col="1" lig="1"/>
    <piece id="5" len="2" dir="V" col="1" lig="4"/>
    <piece id="6" len="2" dir="V" col="2" lig="3"/>
    <piece id="7" len="2" dir="H" col="2" lig="5"/>
    <piece id="8" len="2" dir="V" col="3" lig="0"/>
    <piece id="9" len="3" dir="V" col="4" lig="0"/>
    <piece id="10" len="2" dir="H" col="4" lig="4"/>
    <piece id="11" len="2" dir="H" col="4" lig="5"/>
    <piece id="12" len="3" dir="V" col="5" lig="0"/>
  </puzzle>
  <puzzle name="pb12" monde="2">
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="0"/>
    <piece id="2" len="2" dir="V" col="0" lig="1"/>
    <piece id="3" len="2" dir="V" col="0" lig="3"/>
    <piece id="4" len="2" dir="H" col="0" lig="5"/>
    <piece id="5" len="3" dir="H" col="1" lig="1"/>
    <piece id="6" len="2" dir="V" col="1" lig="3"/>
    <piece id="7" len="2" dir="H" col="2" lig="0"/>
    <piece id="8" len="2" dir="V" col="3" lig="2"/>
    <piece id="9" len="3" dir="H" col="3" lig="4"/>
    <piece id="10" len="2" dir="V" col="4" lig="0"/>
    <piece id="11" len="2" dir="H" col="4" lig="3"/>
    <piece id="12" len="3" dir="V" col="5" lig="0"/>
  </puzzle>
  <puzzle name="pb13" monde="2">
    <!-- Fait par Amina Djelloul -->
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
    <piece id="1" len="3" dir="V" col="0" lig="3"/>
    <piece id="2" len="3" dir="H" col="2" lig="5"/>
    <piece id="3" len="3" dir="H" col="3" lig="0"/>
    <piece id="4" len="3" dir="V" col="3" lig="2"/>
    <piece id="5" len="2" dir="V" col="5" lig="2"/>
    <piece id="6" len="2" dir="V" col="5" lig="4"/>
  </puzzle>
  <puzzle name="pb14" monde="2">
    <piece id="0" len="2" dir="H" col="0" lig="2"/>
    <piece id="1" len="2" dir="V" col="0" lig="0"/>
    <piece id="2" len="3" dir="H" col="0" lig="3"/>
    <piece id="3" len="2" dir="H" col="0" lig="5"/>
    <piece id="4" len="2" dir="V" col="2" lig="4"/>
    <piece id="5" len="3" dir="H" col="3" lig="0"/>
    <piece id="6" len="2" dir="V" col="3" lig="1"/>
    <piece id="7" len="2" dir="H" col="3" lig="5"/>
    <piece id="8" len="2" dir="V" col="4" lig="2"/>
    <piece id="9" len="2" dir="H" col="4" lig="4"/>
    <piece id="10" len="3" dir="V" col="5" lig="1"/>
  </puzzle>
  <puzzle name="pb15" monde="2">
    <!-- Fait par Laureline CoutÃ© -->
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="2" dir="V" col="0" lig="3"/>
    <piece id="2" len="2" dir="V" col="1" lig="0"/>
    <piece id="3" len="2" dir="V" col="2" lig="4"/>
    <piece id="4" len="3" dir="V" col="3" lig="0"/>
    <piece id="5" len="3" dir="H" col="3" lig="4"/>
    <piece id="6" len="2" dir="V" col="4" lig="2"/>
    <piece id="7" len="2" dir="V" col="5" lig="1"/>
  </puzzle>
  <puzzle name="pb16" monde="2">
    <!-- Fait par Meryna Rathisilas -->
    <piece id="0" len="3" dir="H" col="0" lig="2"/>
    <piece id="1" len="2" dir="H" col="0" lig="0"/>
    <piece id="2" len="2" dir="V" col="0" lig="3"/>
    <piece id="3" len="2" dir="V" col="1" lig="4"/>
    <piece id="4" len="2" dir="V" col="2" lig="0"/>
    <piece id="5" len="3" dir="H" col="2" lig="5"/>
    <piece id="6" len="3" dir="V" col="3" lig="2"/>
    <piece id="7" len="2" dir="V" col="4" lig="1"/>
    <piece id="8" len="2" dir="V" col="4" lig="3"/>
    <piece id="9" len="2" dir="V" col="5" lig="0"/>
    <piece id="10" len="2" dir="V" col="5" lig="4"/>
  </puzzle>
  <puzzle name="pb17" monde="3">
    <!-- Fait par Sarah Tardiveau -->
    <piece id="0" len="2" dir="H" col="1" lig="2"/>
    <piece id="1" len="3" dir="V" col="0" lig="0"/>
    <piece id="2" len="3" dir="V" col="0" lig="3"/>
    <piece id="3" len="2" dir="V" col="1" lig="0"/>
    <piece id="4" len="3" dir="H" col="1" lig="3"/>
    <piece id="5" len="2" dir="V" col="1" lig="4"/>
    <piece id="6" len="3" dir="H" col="2" lig="0"/>
    <piece id="7" len="2" dir="V" col="2" lig="4"/>
    <piece id="8" len="2" dir="H" col="3" lig="1"/>
    <piece id="9" len="2" dir="H" col="3" lig="4"/>
    <piece id="10" len="2" dir="H" col="3" lig="5"/>
    <piece id="11" len="2" dir="V" col="4" lig="2"/>
